[project]
name = "qr-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Basir Naji", email = "basirnaji007@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pillow>=12.3.0",
    "qrcode>=8.2",
]

[project.scripts]
qr-generator = "qr_generator.main:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
